export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILURE = "ADD_PRODUCT_TO_CART_FAILURE";

export const UPDATE_PRODUCT_IN_CART_REQUEST = "UPDATE_PRODUCT_IN_CART_REQUEST";
export const UPDATE_PRODUCT_IN_CART_SUCCESS = "UPDATE_PRODUCT_IN_CART_SUCCESS";
export const UPDATE_PRODUCT_IN_CART_FAILURE = "UPDATE_PRODUCT_IN_CART_FAILURE";

export const CLEAR_PRODUCT_ITEM_CART_REQUEST = 'CLEAR_CLEAR_PRODUCT_ITEM_CART_REQUEST'

export const DELETE_PRODUCT_FROM_CART_REQUEST =
  "DELETE_PRODUCT_FROM_CART_REQUEST";
export const DELETE_PRODUCT_FROM_CART_SUCCESS =
  "DELETE_PRODUCT_FROM_CART_SUCCESS";
export const DELETE_PRODUCT_FROM_CART_FAILURE =
  "DELETE_PRODUCT_FROM_CART_FAILURE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE'
